server:
  port: 9080
spring:
  datasource:
    url: jdbc:mysql://localhost/order_service_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: pass
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://mydb.cti1pnc10c3g.rds.cn-north-1.amazonaws.com.cn/order_service_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
  flyway:
    enabled: true
